version: "3"
services:
  streamlit:
    build:
      context: .
      dockerfile: streamlit.Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./model:/app/model
