name: hfmrs
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - transformers
  - jupyterlab
  - matplotlib
  - scikit-learn
  - streamlit
  - seaborn
  - plotly
  - fastapi
  - uvicorn
  - pytorch
  - sentence-transformers
